---
- name: Manage Arch-based OS configuration
  hosts: your_host
  become: true
  gather_facts: true

  roles:
    - arch_keyring
    - update_pacman
    - install_yay
    - install_snapd
    - configure_zsh
